-- =====================================================================
-- ACTION360 :: CI/CD bootstrap (run ONCE as ACCOUNTADMIN; not run by the pipeline)
-- GitHub Actions authenticates with OIDC (workload identity federation):
--   * no password / private key / token is stored in the repo or in GitHub secrets
--   * Snowflake trusts only tokens issued for repo bakiyaswanth/Nexus-360, branch main
-- The CI service user runs as least-privilege role ACTION360_DEPLOYER, which owns ACTION360_DB.
-- =====================================================================
USE ROLE ACCOUNTADMIN;

-- 1. Deployer role ----------------------------------------------------------------
CREATE ROLE IF NOT EXISTS ACTION360_DEPLOYER COMMENT = 'Owns and deploys ACTION360_DB objects (CI/CD)';
GRANT ROLE ACTION360_DEPLOYER TO ROLE SYSADMIN;                 -- keep admins in the hierarchy
GRANT ROLE ACTION360_ANALYST TO ROLE ACTION360_DEPLOYER;        -- lets the deployer manage business-user grants
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE ACTION360_WH TO ROLE ACTION360_DEPLOYER;
GRANT USAGE ON COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU TO ROLE ACTION360_DEPLOYER;   -- Streamlit container runtime
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ACTION360_DEPLOYER;                          -- resume the enrichment task
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACTION360_DEPLOYER;              -- AI functions, search, agents

-- 2. Transfer ownership of the project database to the deployer (grants preserved) ----
ALTER TASK IF EXISTS ACTION360_DB.CORE.ACTION360_ENRICH_TASK SUSPEND;
GRANT OWNERSHIP ON DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL DYNAMIC TABLES IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STAGES IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STREAMS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TASKS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL FUNCTIONS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL PROCEDURES IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL CORTEX SEARCH SERVICES IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SEMANTIC VIEWS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL AGENTS IN DATABASE ACTION360_DB TO ROLE ACTION360_DEPLOYER COPY CURRENT GRANTS;
-- Streamlit ownership cannot be transferred: drop it; the deployer recreates it on the next deploy
DROP STREAMLIT IF EXISTS ACTION360_DB.APP.ACTION360_APP;

-- 3. CI service user (OIDC, no credentials) ----------------------------------------
CREATE USER IF NOT EXISTS SVC_GITHUB_ACTIONS
  TYPE = SERVICE
  DEFAULT_ROLE = ACTION360_DEPLOYER
  DEFAULT_WAREHOUSE = ACTION360_WH
  COMMENT = 'GitHub Actions CI/CD for ACTION360 via OIDC (bakiyaswanth/Nexus-360, main)'
  WORKLOAD_IDENTITY = (
    TYPE = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    -- GitHub's immutable-ID subject format: repo:<owner>@<owner_id>/<repo>@<repo_id>:ref:refs/heads/<branch>
    -- (copy it verbatim from a failed run's error message if the repo is recreated / transferred)
    SUBJECT = 'repo:bakiyaswanth@63598964/Nexus-360@1401278976:ref:refs/heads/main'
  );
GRANT ROLE ACTION360_DEPLOYER TO USER SVC_GITHUB_ACTIONS;

-- 4. Local development uses the same role, so local and CI deploys own objects identically
GRANT ROLE ACTION360_DEPLOYER TO USER BAKIYASWANTH;
