-- =====================================================================
-- ACTION360 :: 07 Cortex Search (two targeted corpora)
--   AI.INTERACTION_SEARCH  call transcripts + interaction notes (last 12 months), filterable by CUSTOMER_ID etc.
--   AI.KNOWLEDGE_SEARCH    product / policy / offer / underwriting / servicing knowledge chunks
-- Corpus is intentionally small (cost) and carries source metadata so the UI can cite evidence.
-- =====================================================================
USE WAREHOUSE ACTION360_WH;
USE SCHEMA ACTION360_DB.AI;

CREATE OR REPLACE VIEW ACTION360_DB.AI.V_INTERACTION_CORPUS AS
SELECT i.INTERACTION_ID AS DOC_ID, i.CUSTOMER_ID, i.INDUSTRY_TYPE, i.CHANNEL, i.TOPIC,
  i.INTERACTION_TS::DATE AS INTERACTION_DATE, i.RESOLUTION_STATUS, IFF(i.IS_COMPLAINT, 'Y', 'N') AS IS_COMPLAINT,
  CASE WHEN COALESCE(t.AI_SENTIMENT_SCORE, i.RULE_SENTIMENT) <= -0.3 THEN 'NEGATIVE'
       WHEN COALESCE(t.AI_SENTIMENT_SCORE, i.RULE_SENTIMENT) < 0.1 THEN 'NEUTRAL' ELSE 'POSITIVE' END AS SENTIMENT,
  COALESCE(t.AI_INTENT, 'not_enriched') AS INTENT,
  COALESCE(t.SOURCE_FILE, 'FACT_INTERACTION:' || i.INTERACTION_ID) AS SOURCE_FILE,
  COALESCE(t.SOURCE_TYPE, 'INTERACTION_NOTE') AS SOURCE_TYPE,
  '[' || TO_VARCHAR(i.INTERACTION_TS, 'YYYY-MM-DD') || ' ' || i.CHANNEL || ' | ' || i.TOPIC || ' | ' || i.RESOLUTION_STATUS || '] '
    || i.NOTE || COALESCE('\nTRANSCRIPT:\n' || t.TRANSCRIPT_TEXT, '') AS CONTENT
FROM ACTION360_DB.CORE.FACT_INTERACTION i
LEFT JOIN ACTION360_DB.CORE.CALL_TRANSCRIPT t ON t.INTERACTION_ID = i.INTERACTION_ID
WHERE i.INTERACTION_TS >= '2025-10-02';

CREATE OR REPLACE CORTEX SEARCH SERVICE ACTION360_DB.AI.INTERACTION_SEARCH
  ON CONTENT
  ATTRIBUTES CUSTOMER_ID, INDUSTRY_TYPE, CHANNEL, TOPIC, INTERACTION_DATE, RESOLUTION_STATUS, IS_COMPLAINT, SENTIMENT, INTENT, SOURCE_TYPE
  WAREHOUSE = ACTION360_WH
  TARGET_LAG = '1 day'
  COMMENT = 'Customer interaction evidence (transcripts + notes). Always filter by CUSTOMER_ID for customer questions.'
AS SELECT DOC_ID, CUSTOMER_ID, INDUSTRY_TYPE, CHANNEL, TOPIC, INTERACTION_DATE, RESOLUTION_STATUS, IS_COMPLAINT, SENTIMENT, INTENT,
          SOURCE_FILE, SOURCE_TYPE, CONTENT
   FROM ACTION360_DB.AI.V_INTERACTION_CORPUS;

CREATE OR REPLACE CORTEX SEARCH SERVICE ACTION360_DB.AI.KNOWLEDGE_SEARCH
  ON CHUNK_TEXT
  ATTRIBUTES DOC_TYPE, INDUSTRY_TYPE, PRODUCT, OFFER_IDS, TITLE
  WAREHOUSE = ACTION360_WH
  TARGET_LAG = '1 day'
  COMMENT = 'Product, policy, offer, underwriting and servicing knowledge'
AS SELECT CHUNK_ID, DOC_ID, TITLE, SECTION, DOC_TYPE, INDUSTRY_TYPE, PRODUCT, OFFER_IDS, SOURCE_FILE, CHUNK_TEXT
   FROM ACTION360_DB.CORE.KNOWLEDGE_CHUNK;
