-- =====================================================================
-- ACTION360 :: offer pipeline diagnostics (read-only)
-- Run any time:  python scripts/run_sql.py sql/diagnose_offers.sql   (or paste into a worksheet)
-- Every query returns one summary row per check; ISSUES = 0 means healthy.
-- =====================================================================
USE ROLE ACTION360_DEPLOYER;
USE WAREHOUSE ACTION360_WH;
USE SCHEMA ACTION360_DB.CORE;

-- 1. Catalogue + eligibility coverage ------------------------------------------------
SELECT 'catalogue' CHECK_NAME,
       COUNT(*) TOTAL_OFFERS, COUNT_IF(IS_ACTIVE) ACTIVE_OFFERS,
       COUNT_IF(OFFER_NAME IS NULL OR OFFER_DESCRIPTION IS NULL OR OFFER_CATEGORY IS NULL) ISSUES_MISSING_METADATA
FROM OFFER_CATALOG;

SELECT 'offers_without_hard_rules' CHECK_NAME, COUNT(*) ISSUES, ARRAY_AGG(o.OFFER_ID) OFFERS
FROM OFFER_CATALOG o
WHERE o.IS_ACTIVE AND NOT EXISTS (SELECT 1 FROM OFFER_ELIGIBILITY_RULE r WHERE r.OFFER_ID = o.OFFER_ID AND r.IS_HARD);

SELECT 'orphaned_rule_offer_ids' CHECK_NAME, COUNT(*) ISSUES, ARRAY_AGG(DISTINCT r.OFFER_ID) OFFERS
FROM OFFER_ELIGIBILITY_RULE r LEFT JOIN OFFER_CATALOG o ON o.OFFER_ID = r.OFFER_ID WHERE o.OFFER_ID IS NULL;

SELECT 'eligibility_rows' CHECK_NAME,
       COUNT(*) CUSTOMER_OFFER_ROWS, COUNT_IF(IS_ELIGIBLE) ELIGIBLE_ROWS,
       COUNT(DISTINCT CUSTOMER_ID) CUSTOMERS_EVALUATED,
       COUNT_IF(IS_ELIGIBLE IS NULL) ISSUES_INVALID_ELIGIBILITY_STATE,
       COUNT_IF(IS_ELIGIBLE AND ARRAY_SIZE(FAILED_RULES) > 0) + COUNT_IF(NOT IS_ELIGIBLE AND ARRAY_SIZE(FAILED_RULES) = 0) ISSUES_INCONSISTENT_RULES
FROM OFFER_ELIGIBILITY;

SELECT 'duplicate_customer_offer_rows' CHECK_NAME, COUNT(*) ISSUES
FROM (SELECT CUSTOMER_ID, OFFER_ID FROM OFFER_ELIGIBILITY GROUP BY 1, 2 HAVING COUNT(*) > 1);

SELECT 'orphaned_eligibility_offer_ids' CHECK_NAME, COUNT(*) ISSUES
FROM OFFER_ELIGIBILITY e LEFT JOIN OFFER_CATALOG o ON o.OFFER_ID = e.OFFER_ID WHERE o.OFFER_ID IS NULL;

SELECT 'customers_with_zero_eligible_offers' CHECK_NAME, COUNT(*) CUSTOMERS
FROM (SELECT c.CUSTOMER_ID FROM CUSTOMER_360 c LEFT JOIN OFFER_ELIGIBILITY e ON e.CUSTOMER_ID = c.CUSTOMER_ID AND e.IS_ELIGIBLE
      GROUP BY 1 HAVING COUNT(e.OFFER_ID) = 0);

-- 2. Recommendation integrity (NBA_CANDIDATE rank 1 = what the UI shows) ------------
SELECT 'recommended_offer_integrity' CHECK_NAME,
       COUNT(*) RECOMMENDATIONS,
       COUNT(n.SELECTED_OFFER) WITH_OFFER,
       COUNT_IF(n.SELECTED_OFFER IS NOT NULL AND COALESCE(e.IS_ELIGIBLE, FALSE) = FALSE) ISSUES_RECOMMENDED_OFFER_NOT_ELIGIBLE,
       COUNT_IF(n.SELECTED_OFFER IS NOT NULL AND o.OFFER_ID IS NULL) ISSUES_RECOMMENDED_OFFER_NOT_IN_CATALOGUE,
       COUNT_IF(n.OFFER_MODE = 'REQUIRED' AND n.SELECTED_OFFER IS NULL) ISSUES_REQUIRED_OFFER_MISSING
FROM NBA_CANDIDATE n
LEFT JOIN OFFER_ELIGIBILITY e ON e.CUSTOMER_ID = n.CUSTOMER_ID AND e.OFFER_ID = n.SELECTED_OFFER:offer_id::STRING
LEFT JOIN OFFER_CATALOG o ON o.OFFER_ID = n.SELECTED_OFFER:offer_id::STRING
WHERE n.ELIGIBLE_RANK = 1;

SELECT 'customers_with_duplicate_rank1' CHECK_NAME, COUNT(*) ISSUES
FROM (SELECT CUSTOMER_ID FROM NBA_CANDIDATE WHERE ELIGIBLE_RANK = 1 GROUP BY 1 HAVING COUNT(*) > 1);

SELECT 'customers_without_rank1' CHECK_NAME, COUNT(*) ISSUES
FROM CUSTOMER_360 c WHERE NOT EXISTS (SELECT 1 FROM NBA_CANDIDATE n WHERE n.CUSTOMER_ID = c.CUSTOMER_ID AND n.ELIGIBLE_RANK = 1);

SELECT 'customer_360_vs_engine_offer_drift' CHECK_NAME, COUNT(*) ISSUES
FROM CUSTOMER_360 c JOIN NBA_CANDIDATE n ON n.CUSTOMER_ID = c.CUSTOMER_ID AND n.ELIGIBLE_RANK = 1
WHERE EQUAL_NULL(c.RECOMMENDED_OFFER_ID, n.SELECTED_OFFER:offer_id::STRING) = FALSE
   OR c.RECOMMENDED_ACTION <> n.ACTION_CODE;

-- 3. Why customers have no offer (explains every "No eligible offer found" in the UI) --
SELECT n.OFFER_MODE, c.INDUSTRY_TYPE, n.ACTION_CODE,
       CASE WHEN n.OFFER_MODE = 'NONE' THEN 'NO_OFFER_REQUIRED (servicing action)'
            WHEN ARRAY_SIZE(n.INELIGIBLE_OFFERS) = 0 THEN 'NO_ELIGIBLE_OFFER: no catalogue offer for this category + line of business'
            ELSE 'NO_ELIGIBLE_OFFER: category offers failed hard rules' END REASON,
       COUNT(*) CUSTOMERS,
       COUNT_IF(EXISTS (SELECT 1 FROM OFFER_ELIGIBILITY e WHERE e.CUSTOMER_ID = n.CUSTOMER_ID AND e.IS_ELIGIBLE)) HAVE_OTHER_ELIGIBLE_OFFERS
FROM NBA_CANDIDATE n JOIN CUSTOMER_360 c USING (CUSTOMER_ID)
WHERE n.ELIGIBLE_RANK = 1 AND n.SELECTED_OFFER IS NULL
GROUP BY 1, 2, 3, 4 ORDER BY CUSTOMERS DESC;

-- 4. Persisted recommendations (NBA_RECOMMENDATION / ACTION_AUDIT) -------------------
SELECT 'persisted_recommendations' CHECK_NAME,
       COUNT(*) RECOMMENDATIONS,
       COUNT_IF(SELECTED_ACTION IS NULL) ISSUES_NULL_ACTION,
       COUNT_IF(OFFER_ID IS NULL) WITHOUT_OFFER,
       COUNT_IF(OFFER_ID IS NOT NULL AND ELIGIBILITY_RESULT:selected_offer IS NULL) ISSUES_OFFER_WITHOUT_ELIGIBILITY_RESULT
FROM NBA_RECOMMENDATION;

SELECT 'persisted_offer_not_in_catalogue' CHECK_NAME, COUNT(*) ISSUES
FROM NBA_RECOMMENDATION r LEFT JOIN OFFER_CATALOG o ON o.OFFER_ID = r.OFFER_ID
WHERE r.OFFER_ID IS NOT NULL AND o.OFFER_ID IS NULL;

SELECT 'audit_offer_states' CHECK_NAME, ELIGIBILITY_STATUS, USER_ACTION, COUNT(*) RECORDS
FROM ACTION_AUDIT GROUP BY 2, 3 ORDER BY 4 DESC;

SELECT 'audit_approved_ineligible_offer' CHECK_NAME, COUNT(*) ISSUES
FROM ACTION_AUDIT a JOIN OFFER_ELIGIBILITY e ON e.CUSTOMER_ID = a.CUSTOMER_ID AND e.OFFER_ID = a.OFFER_ID
WHERE a.USER_ACTION = 'APPROVED' AND NOT e.IS_ELIGIBLE;
