-- =====================================================================
-- ACTION360 :: 05 Decision engine (eligibility + next-best-action) and Customer 360
--   OFFER_CATALOG / OFFER_ELIGIBILITY_RULE   hard, auditable business rules
--   OFFER_ELIGIBILITY (DT)                  rule-by-rule evaluation per customer x offer
--   ACTION_CATALOG / NBA_WEIGHT / NBA_GUARDRAIL   configurable, transparent NBA framework
--   NBA_CANDIDATE (DT)                      every candidate action scored, gated and ranked
--   CUSTOMER_360  (DT)                      unified customer view incl. recommended action
--   NBA_RECOMMENDATION / ACTION_AUDIT / AI_USAGE_METRICS / EVALUATION_CASE
-- LLMs never decide eligibility or the selected action: they only explain and personalise.
-- =====================================================================
USE WAREHOUSE ACTION360_WH;
USE SCHEMA ACTION360_DB.CORE;

MERGE INTO APP_CONFIG t USING (SELECT 'MIN_ACTION_SCORE' k, '0.40' v, 'Candidate actions scoring below this fall back to NO_ACTION_MONITOR' d) s
ON t.CONFIG_KEY = s.k WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES (s.k, s.v, s.d);

-- ---------------------------------------------------------------------
-- Offers and hard eligibility rules
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE OFFER_CATALOG (
  OFFER_ID STRING PRIMARY KEY, OFFER_NAME STRING, INDUSTRY_TYPE STRING, OFFER_CATEGORY STRING, PRIORITY INT,
  OFFER_DESCRIPTION STRING, VALUE_TO_CUSTOMER STRING, POLICY_DOC_ID STRING, IS_ACTIVE BOOLEAN DEFAULT TRUE);
INSERT INTO OFFER_CATALOG (OFFER_ID, OFFER_NAME, INDUSTRY_TYPE, OFFER_CATEGORY, PRIORITY, OFFER_DESCRIPTION, VALUE_TO_CUSTOMER, POLICY_DOC_ID) VALUES
 ('OFF_RATE_MATCH','Home/Personal loan rate match','LENDING','RETENTION',90,'Reprice up to 60 bps below current rate (floor 8.35%), valid 30 days','Lower EMI','retention_offer_playbook_lending'),
 ('OFF_RETENTION_CASHBACK','Retention cashback INR 5,000','ALL','RETENTION',60,'One-time cashback for at-risk customers in good standing','INR 5,000','retention_offer_playbook_lending'),
 ('OFF_LOYALTY_RENEWAL','Loyalty renewal discount 10%','INSURANCE','RETENTION',80,'10% off renewal premium for loyal low-claim customers','10% premium','motor_home_renewal_guidelines'),
 ('OFF_FEE_WAIVER','Annual card fee waiver (goodwill)','LENDING','SERVICE_RECOVERY',80,'Goodwill annual fee waiver after a service failure','Fee waived','complaint_service_recovery_standard'),
 ('OFF_HARDSHIP_PLAN','Hardship assistance plan','LENDING','HARDSHIP',95,'EMI restructure / up to 3-month payment holiday / late-fee waiver on approval','Breathing room','hardship_collections_policy'),
 ('OFF_PREMIUM_DEFERRAL','Premium instalment / grace extension','INSURANCE','HARDSHIP',90,'Switch to monthly mode or extend grace to avoid lapse','Keeps cover active','motor_home_renewal_guidelines'),
 ('OFF_CARD_UPGRADE','Voyager premium travel card upgrade','LENDING','UPGRADE',85,'Instant upgrade to premium travel card','Lounge + 5x travel rewards','voyager_card_and_topup_brochure'),
 ('OFF_TOPUP_LOAN','Pre-approved top-up loan','LENDING','UPGRADE',70,'Top-up of up to 20% of original principal at existing rate','Funds at current rate','voyager_card_and_topup_brochure'),
 ('OFF_NCB_PROTECT','No-claim bonus protector','INSURANCE','UPGRADE',50,'Protect NCB at renewal','Protects NCB','motor_home_renewal_guidelines'),
 ('OFF_FAMILY_FLOATER','Family floater migration','INSURANCE','CROSS_SELL',90,'Migrate individual health to family floater with continuity credit','Covers spouse + children','family_floater_term_life_guide'),
 ('OFF_TERM_LIFE','Term life cover','ALL','CROSS_SELL',75,'Pure protection 10-20x income','Family protection','family_floater_term_life_guide');

CREATE OR REPLACE TABLE OFFER_ELIGIBILITY_RULE (
  RULE_ID STRING PRIMARY KEY, OFFER_ID STRING, ATTRIBUTE STRING, OPERATOR STRING, THRESHOLD_NUM FLOAT, THRESHOLD_TEXT STRING,
  RULE_DESCRIPTION STRING, IS_HARD BOOLEAN DEFAULT TRUE) COMMENT = 'All rules for an offer must pass (AND). Operators: >=, <=, =, IN';
INSERT INTO OFFER_ELIGIBILITY_RULE (RULE_ID, OFFER_ID, ATTRIBUTE, OPERATOR, THRESHOLD_NUM, THRESHOLD_TEXT, RULE_DESCRIPTION) VALUES
 ('R01','OFF_RATE_MATCH','HOLDS_HL_OR_PL','>=',1,NULL,'Holds a home or personal loan'),
 ('R02','OFF_RATE_MATCH','TENURE_MONTHS','>=',24,NULL,'Tenure >= 24 months'),
 ('R03','OFF_RATE_MATCH','MISSED_6M','<=',0,NULL,'No missed instalments in 6 months'),
 ('R04','OFF_RATE_MATCH','MAX_DAYS_LATE_90D','<=',5,NULL,'Max days past due (90d) <= 5'),
 ('R05','OFF_RATE_MATCH','SEGMENT','IN',NULL,'AFFLUENT,PREMIER','Segment is AFFLUENT or PREMIER'),
 ('R06','OFF_RATE_MATCH','CHURN_RISK','>=',0.40,NULL,'Churn risk >= 0.40'),
 ('R07','OFF_RETENTION_CASHBACK','CHURN_RISK','>=',0.50,NULL,'Churn risk >= 0.50'),
 ('R08','OFF_RETENTION_CASHBACK','MISSED_6M','<=',0,NULL,'No missed instalments in 6 months'),
 ('R09','OFF_RETENTION_CASHBACK','MAX_DAYS_LATE_90D','<=',30,NULL,'Max days past due (90d) <= 30'),
 ('R10','OFF_RETENTION_CASHBACK','RESTRUCTURE_FLAG','<=',0,NULL,'No open hardship / restructure request'),
 ('R11','OFF_LOYALTY_RENEWAL','DAYS_TO_RENEWAL','<=',60,NULL,'Renewal within 60 days'),
 ('R12','OFF_LOYALTY_RENEWAL','CLAIMS_12M','<=',1,NULL,'At most 1 claim in 12 months'),
 ('R13','OFF_LOYALTY_RENEWAL','MISSED_6M','<=',0,NULL,'No missed premiums in 6 months'),
 ('R14','OFF_LOYALTY_RENEWAL','TENURE_MONTHS','>=',36,NULL,'Tenure >= 36 months'),
 ('R15','OFF_FEE_WAIVER','HAS_CC','>=',1,NULL,'Holds a credit card'),
 ('R16','OFF_FEE_WAIVER','MISSED_6M','<=',0,NULL,'No missed payments in 6 months'),
 ('R17','OFF_FEE_WAIVER','COMPLAINTS_90D','>=',1,NULL,'At least one complaint in 90 days'),
 ('R18','OFF_HARDSHIP_PLAN','PAYMENT_DISTRESS','>=',1,NULL,'Missed/partial instalment in 6m or >= 15 days past due'),
 ('R19','OFF_HARDSHIP_PLAN','CREDIT_SCORE','>=',550,NULL,'Credit score >= 550'),
 ('R20','OFF_PREMIUM_DEFERRAL','PAYMENT_DISTRESS','>=',1,NULL,'Missed/partial premium in 6m or >= 15 days late'),
 ('R21','OFF_PREMIUM_DEFERRAL','TENURE_MONTHS','>=',6,NULL,'Tenure >= 6 months'),
 ('R22','OFF_CARD_UPGRADE','HAS_CC','>=',1,NULL,'Holds a credit card'),
 ('R23','OFF_CARD_UPGRADE','CREDIT_SCORE','>=',750,NULL,'Credit score >= 750'),
 ('R24','OFF_CARD_UPGRADE','MISSED_6M','<=',0,NULL,'No missed payments in 6 months'),
 ('R25','OFF_CARD_UPGRADE','LATE_6M','<=',0,NULL,'No late payments in 6 months'),
 ('R26','OFF_CARD_UPGRADE','SPEND_TREND','>=',1.10,NULL,'Card spend up >= 10% vs prior 3 months'),
 ('R27','OFF_CARD_UPGRADE','UNRESOLVED_COUNT','<=',0,NULL,'No unresolved complaints'),
 ('R28','OFF_TOPUP_LOAN','HOLDS_HL_OR_PL','>=',1,NULL,'Holds a home or personal loan'),
 ('R29','OFF_TOPUP_LOAN','CREDIT_SCORE','>=',740,NULL,'Credit score >= 740'),
 ('R30','OFF_TOPUP_LOAN','TENURE_MONTHS','>=',12,NULL,'Tenure >= 12 months'),
 ('R31','OFF_TOPUP_LOAN','MISSED_6M','<=',0,NULL,'No missed instalments in 6 months'),
 ('R32','OFF_TOPUP_LOAN','UNRESOLVED_COUNT','<=',0,NULL,'No unresolved complaints'),
 ('R33','OFF_NCB_PROTECT','HAS_MOTOR','>=',1,NULL,'Holds motor insurance'),
 ('R34','OFF_NCB_PROTECT','TENURE_MONTHS','>=',12,NULL,'Tenure >= 12 months'),
 ('R35','OFF_FAMILY_FLOATER','HAS_HEALTH','>=',1,NULL,'Holds individual health insurance'),
 ('R36','OFF_FAMILY_FLOATER','HAS_FAMILY_FLOATER','<=',0,NULL,'Does not already hold a family floater'),
 ('R37','OFF_FAMILY_FLOATER','AGE','<=',55,NULL,'Age <= 55'),
 ('R38','OFF_FAMILY_FLOATER','MISSED_6M','<=',0,NULL,'No missed premiums in 6 months'),
 ('R39','OFF_TERM_LIFE','HAS_TERM_LIFE','<=',0,NULL,'No existing term life policy'),
 ('R40','OFF_TERM_LIFE','AGE','<=',60,NULL,'Age <= 60'),
 ('R41','OFF_TERM_LIFE','MISSED_6M','<=',0,NULL,'No missed payments in 6 months');

-- ---------------------------------------------------------------------
-- OFFER_ELIGIBILITY  (every rule evaluated, every outcome explainable)
-- ---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE OFFER_ELIGIBILITY
  TARGET_LAG = 'DOWNSTREAM' WAREHOUSE = ACTION360_WH REFRESH_MODE = FULL
  COMMENT = 'Deterministic rule evaluation per customer x offer'
AS
WITH attr AS (
  SELECT f.CUSTOMER_ID, f.INDUSTRY_TYPE, f.SEGMENT,
    OBJECT_CONSTRUCT(
      'TENURE_MONTHS', f.TENURE_MONTHS::FLOAT, 'CREDIT_SCORE', f.CREDIT_SCORE::FLOAT, 'AGE', f.AGE::FLOAT,
      'MISSED_6M', f.MISSED_6M::FLOAT, 'LATE_6M', f.LATE_6M::FLOAT, 'MAX_DAYS_LATE_90D', f.MAX_DAYS_LATE_90D::FLOAT,
      'DAYS_TO_RENEWAL', f.DAYS_TO_RENEWAL::FLOAT, 'CLAIMS_12M', f.CLAIMS_12M::FLOAT, 'SPEND_TREND', COALESCE(f.SPEND_TREND, 0)::FLOAT,
      'COMPLAINTS_90D', f.COMPLAINTS_90D::FLOAT, 'UNRESOLVED_COUNT', f.UNRESOLVED_COUNT::FLOAT, 'RESTRUCTURE_FLAG', f.RESTRUCTURE_FLAG::FLOAT,
      'HAS_CC', f.HAS_CC::FLOAT, 'HAS_HEALTH', f.HAS_HEALTH::FLOAT, 'HAS_FAMILY_FLOATER', f.HAS_FAMILY_FLOATER::FLOAT,
      'HAS_TERM_LIFE', f.HAS_TERM_LIFE::FLOAT, 'HAS_MOTOR', f.HAS_MOTOR::FLOAT,
      'HOLDS_HL_OR_PL', GREATEST(f.HAS_HL, f.HAS_PL)::FLOAT,
      'PAYMENT_DISTRESS', IFF(f.MISSED_6M >= 1 OR f.MAX_DAYS_LATE_90D >= 15, 1, 0)::FLOAT,
      'CHURN_RISK', r.CHURN_RISK::FLOAT) NUM
  FROM CUSTOMER_FEATURES f JOIN CUSTOMER_RISK r USING (CUSTOMER_ID)),
ev AS (
  SELECT a.CUSTOMER_ID, o.OFFER_ID, o.OFFER_NAME, o.OFFER_CATEGORY, o.PRIORITY, o.POLICY_DOC_ID, r.RULE_ID, r.RULE_DESCRIPTION,
    CASE WHEN r.ATTRIBUTE = 'SEGMENT' THEN a.SEGMENT ELSE TO_VARCHAR(a.NUM[r.ATTRIBUTE]) END ACTUAL_VALUE,
    COALESCE(CASE r.OPERATOR
      WHEN '>=' THEN a.NUM[r.ATTRIBUTE]::FLOAT >= r.THRESHOLD_NUM
      WHEN '<=' THEN a.NUM[r.ATTRIBUTE]::FLOAT <= r.THRESHOLD_NUM
      WHEN '='  THEN a.NUM[r.ATTRIBUTE]::FLOAT = r.THRESHOLD_NUM
      WHEN 'IN' THEN ARRAY_CONTAINS(a.SEGMENT::VARIANT, SPLIT(r.THRESHOLD_TEXT, ','))
    END, FALSE) AS PASSED
  FROM attr a
  JOIN OFFER_CATALOG o ON o.IS_ACTIVE AND o.INDUSTRY_TYPE IN (a.INDUSTRY_TYPE, 'ALL')
  JOIN OFFER_ELIGIBILITY_RULE r ON r.OFFER_ID = o.OFFER_ID AND r.IS_HARD)
SELECT CUSTOMER_ID, OFFER_ID, ANY_VALUE(OFFER_NAME) OFFER_NAME, ANY_VALUE(OFFER_CATEGORY) OFFER_CATEGORY,
  ANY_VALUE(PRIORITY) PRIORITY, ANY_VALUE(POLICY_DOC_ID) POLICY_DOC_ID,
  BOOLAND_AGG(PASSED) IS_ELIGIBLE,
  ARRAY_AGG(IFF(PASSED, NULL, RULE_DESCRIPTION || ' (actual: ' || COALESCE(ACTUAL_VALUE, 'n/a') || ')')) FAILED_RULES,
  ARRAY_AGG(IFF(PASSED, RULE_DESCRIPTION, NULL)) PASSED_RULES,
  COUNT(*) RULES_EVALUATED
FROM ev GROUP BY CUSTOMER_ID, OFFER_ID;

-- ---------------------------------------------------------------------
-- Action catalogue, configurable weights and hard guardrails
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE ACTION_CATALOG (
  ACTION_CODE STRING PRIMARY KEY, ACTION_NAME STRING, INDUSTRY_SCOPE STRING, OFFER_CATEGORY STRING, OFFER_MODE STRING,
  BASE_SCORE FLOAT, BUSINESS_PURPOSE STRING, OWNER_ROLE STRING, DEFAULT_CHANNEL STRING);
INSERT INTO ACTION_CATALOG VALUES
 ('SERVICE_RECOVERY','Service recovery call (RM)','ALL','SERVICE_RECOVERY','OPTIONAL',0,'Repair trust after a service failure and prevent attrition of valuable customers','Relationship Manager','CALL'),
 ('COMPLAINT_ESCALATION','Complaint escalation to grievance desk','ALL',NULL,'NONE',0,'Close an aged / repeated complaint within SLA','Grievance Desk','CALL'),
 ('PAYMENT_PLAN_DISCUSSION','Payment-plan / hardship discussion','ALL','HARDSHIP','REQUIRED',0,'Keep a stressed customer current and protect credit outcome','Collections (Hardship)','CALL'),
 ('RETENTION_OFFER','Retention offer','ALL','RETENTION','REQUIRED',0,'Retain a valuable customer showing switching intent','Retention Desk','CALL'),
 ('RENEWAL_REMINDER','Renewal / rate-reset reminder','ALL',NULL,'NONE',0.05,'Secure renewal ahead of expiry / reset','Servicing','EMAIL'),
 ('PRODUCT_UPGRADE','Product upgrade','ALL','UPGRADE','REQUIRED',0,'Grow wallet share with a better-fit product','Sales','APP'),
 ('CROSS_SELL','Cross-sell protection / product','ALL','CROSS_SELL','REQUIRED',0,'Close a detected product or protection gap','Sales','CALL'),
 ('COVERAGE_REVIEW','Coverage review with advisor','INSURANCE','CROSS_SELL','OPTIONAL',0,'Align cover with a life event','Advisor','CALL'),
 ('PROACTIVE_SERVICE_CALL','Proactive service check-in','ALL',NULL,'NONE',0,'Reach out before a dissatisfied customer leaves','Servicing','CALL'),
 ('MISSING_DOCUMENT_REQUEST','Missing-document request','ALL',NULL,'NONE',0,'Unblock a pending review / approval','Operations','EMAIL'),
 ('UNDERWRITING_FOLLOW_UP','Underwriting follow-up','LENDING',NULL,'NONE',0,'Progress an enquiry through credit assessment','Underwriting','CALL'),
 ('CLAIM_FOLLOW_UP','Claim follow-up & settlement timeline','INSURANCE',NULL,'NONE',0,'Resolve a delayed claim - the main retention lever','Claims','CALL'),
 ('NO_ACTION_MONITOR','No action - monitor','ALL',NULL,'NONE',0.15,'Avoid unnecessary contact and cost for stable customers','System','NONE');

CREATE OR REPLACE TABLE NBA_WEIGHT (ACTION_CODE STRING, SIGNAL_NAME STRING, WEIGHT FLOAT, PRIMARY KEY (ACTION_CODE, SIGNAL_NAME))
  COMMENT = 'Score(action) = BASE_SCORE + SUM(weight x signal). Negative weights are explicit business penalties.';
INSERT INTO NBA_WEIGHT VALUES
 ('SERVICE_RECOVERY','SERVICE_RISK',0.40),('SERVICE_RECOVERY','NEG_SENTIMENT',0.20),('SERVICE_RECOVERY','UNRESOLVED',0.15),('SERVICE_RECOVERY','CUSTOMER_VALUE',0.15),('SERVICE_RECOVERY','CHURN_RISK',0.10),
 ('COMPLAINT_ESCALATION','ESCALATED',0.30),('COMPLAINT_ESCALATION','UNRESOLVED',0.25),('COMPLAINT_ESCALATION','COMPLAINTS',0.25),('COMPLAINT_ESCALATION','SERVICE_RISK',0.10),('COMPLAINT_ESCALATION','CUSTOMER_VALUE',-0.20),
 ('PAYMENT_PLAN_DISCUSSION','PAYMENT_RISK',0.50),('PAYMENT_PLAN_DISCUSSION','MISSED_PAYMENTS',0.15),('PAYMENT_PLAN_DISCUSSION','HARDSHIP',0.15),('PAYMENT_PLAN_DISCUSSION','SALARY_DROP',0.10),('PAYMENT_PLAN_DISCUSSION','RESTRUCTURE_REQ',0.10),
 ('RETENTION_OFFER','CHURN_RISK',0.40),('RETENTION_OFFER','CUSTOMER_VALUE',0.20),('RETENTION_OFFER','RENEWAL_PROXIMITY',0.15),('RETENTION_OFFER','COMPETITOR_MENTION',0.15),('RETENTION_OFFER','FORECLOSURE_INTENT',0.10),('RETENTION_OFFER','UNRESOLVED',-0.30),
 ('RENEWAL_REMINDER','RENEWAL_PROXIMITY',0.60),('RENEWAL_REMINDER','CUSTOMER_VALUE',0.10),('RENEWAL_REMINDER','NEG_SENTIMENT',-0.15),
 ('PRODUCT_UPGRADE','UPGRADE_READINESS',0.50),('PRODUCT_UPGRADE','CREDIT_QUALITY',0.20),('PRODUCT_UPGRADE','CUSTOMER_VALUE',0.15),('PRODUCT_UPGRADE','TOPUP_INTENT',0.15),
 ('CROSS_SELL','PRODUCT_GAP',0.35),('CROSS_SELL','LIFE_EVENT',0.25),('CROSS_SELL','CREDIT_QUALITY',0.15),('CROSS_SELL','CUSTOMER_VALUE',0.15),('CROSS_SELL','OPPORTUNITY_SCORE',0.10),
 ('COVERAGE_REVIEW','PRODUCT_GAP',0.40),('COVERAGE_REVIEW','LIFE_EVENT',0.45),('COVERAGE_REVIEW','CUSTOMER_VALUE',0.10),('COVERAGE_REVIEW','RECENCY',0.10),
 ('PROACTIVE_SERVICE_CALL','CHURN_RISK',0.35),('PROACTIVE_SERVICE_CALL','NEG_SENTIMENT',0.20),('PROACTIVE_SERVICE_CALL','RENEWAL_PROXIMITY',0.15),('PROACTIVE_SERVICE_CALL','CUSTOMER_VALUE',0.15),('PROACTIVE_SERVICE_CALL','UNRESOLVED',-0.20),
 ('MISSING_DOCUMENT_REQUEST','DOC_PENDING',0.70),('MISSING_DOCUMENT_REQUEST','RENEWAL_PROXIMITY',0.20),
 ('UNDERWRITING_FOLLOW_UP','TOPUP_INTENT',0.45),('UNDERWRITING_FOLLOW_UP','DOC_PENDING',0.25),('UNDERWRITING_FOLLOW_UP','CREDIT_QUALITY',0.20),
 ('CLAIM_FOLLOW_UP','CLAIM_DELAYED',0.55),('CLAIM_FOLLOW_UP','SERVICE_RISK',0.25),('CLAIM_FOLLOW_UP','RENEWAL_PROXIMITY',0.15),('CLAIM_FOLLOW_UP','NEG_SENTIMENT',0.05);

CREATE OR REPLACE TABLE NBA_GUARDRAIL (GUARDRAIL_ID STRING PRIMARY KEY, ACTION_CODE STRING, SIGNAL_NAME STRING, OPERATOR STRING, THRESHOLD FLOAT, REASON STRING)
  COMMENT = 'If the condition is TRUE the action is BLOCKED regardless of score or LLM output';
INSERT INTO NBA_GUARDRAIL VALUES
 ('G01','PRODUCT_UPGRADE','PAYMENT_RISK','>=',0.30,'Responsible lending: no upsell during payment stress'),
 ('G02','PRODUCT_UPGRADE','UNRESOLVED','>=',0.50,'Resolve the open complaint before selling'),
 ('G03','CROSS_SELL','PAYMENT_RISK','>=',0.30,'Responsible lending: no cross-sell during payment stress'),
 ('G04','CROSS_SELL','UNRESOLVED','>=',0.50,'Resolve the open complaint before selling'),
 ('G05','UNDERWRITING_FOLLOW_UP','PAYMENT_RISK','>=',0.30,'No new credit during payment stress'),
 ('G06','RETENTION_OFFER','PAYMENT_RISK','>=',0.50,'No pricing incentives during payment distress - use hardship path'),
 ('G07','COMPLAINT_ESCALATION','UNRESOLVED','<',0.50,'No open complaint to escalate'),
 ('G08','CLAIM_FOLLOW_UP','CLAIM_DELAYED','<',1,'No delayed claim'),
 ('G09','MISSING_DOCUMENT_REQUEST','DOC_PENDING','<',1,'No pending document'),
 ('G10','PAYMENT_PLAN_DISCUSSION','PAYMENT_RISK','<',0.20,'No payment stress detected'),
 ('G11','SERVICE_RECOVERY','SERVICE_RISK','<',0.25,'No service failure to recover'),
 ('G12','RENEWAL_REMINDER','RENEWAL_PROXIMITY','<=',0,'No renewal / reset within 90 days'),
 ('G13','COVERAGE_REVIEW','PRODUCT_GAP','<=',0,'No coverage gap detected'),
 ('G14','UNDERWRITING_FOLLOW_UP','TOPUP_INTENT','<',1,'No open enquiry to underwrite'),
 ('G15','PROACTIVE_SERVICE_CALL','CHURN_RISK','<',0.25,'Low churn risk - no proactive call needed'),
 ('G16','CROSS_SELL','PRODUCT_GAP','<=',0,'No product / protection gap detected');

-- ---------------------------------------------------------------------
-- NBA_CANDIDATE  (all candidates, scored, gated and ranked)
-- ---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE NBA_CANDIDATE
  TARGET_LAG = 'DOWNSTREAM' WAREHOUSE = ACTION360_WH REFRESH_MODE = FULL
  COMMENT = 'Candidate next-best-actions with transparent score, guardrails and eligibility'
AS
WITH risk_sig AS (
  SELECT r.CUSTOMER_ID, f.KEY::STRING SIGNAL_NAME, f.VALUE::FLOAT SIGNAL_VALUE
  FROM CUSTOMER_RISK r, LATERAL FLATTEN(INPUT => OBJECT_CONSTRUCT('CHURN_RISK', r.CHURN_RISK, 'PAYMENT_RISK', r.PAYMENT_RISK,
                                                               'SERVICE_RISK', r.SERVICE_RISK, 'OPPORTUNITY_SCORE', r.OPPORTUNITY_SCORE)) f),
sig AS (SELECT CUSTOMER_ID, SIGNAL_NAME, SIGNAL_VALUE FROM CUSTOMER_SIGNAL UNION ALL SELECT * FROM risk_sig),
cand AS (
  SELECT f.CUSTOMER_ID, f.INDUSTRY_TYPE, a.*
  FROM CUSTOMER_FEATURES f JOIN ACTION_CATALOG a ON a.INDUSTRY_SCOPE IN ('ALL', f.INDUSTRY_TYPE)),
scored AS (
  SELECT c.CUSTOMER_ID, c.ACTION_CODE,
    ANY_VALUE(c.BASE_SCORE) + COALESCE(SUM(w.WEIGHT * s.SIGNAL_VALUE), 0) SCORE,
    ARRAY_AGG(IFF(w.WEIGHT * s.SIGNAL_VALUE <> 0, OBJECT_CONSTRUCT('signal', w.SIGNAL_NAME, 'weight', w.WEIGHT, 'value', s.SIGNAL_VALUE,
              'contribution', ROUND(w.WEIGHT * s.SIGNAL_VALUE, 4)), NULL)) WITHIN GROUP (ORDER BY ABS(w.WEIGHT * s.SIGNAL_VALUE) DESC) CONTRIBUTIONS
  FROM cand c LEFT JOIN NBA_WEIGHT w ON w.ACTION_CODE = c.ACTION_CODE
  LEFT JOIN sig s ON s.CUSTOMER_ID = c.CUSTOMER_ID AND s.SIGNAL_NAME = w.SIGNAL_NAME
  GROUP BY 1, 2),
guard AS (
  SELECT c.CUSTOMER_ID, c.ACTION_CODE, ARRAY_AGG(g.REASON) BLOCK_REASONS
  FROM cand c JOIN NBA_GUARDRAIL g ON g.ACTION_CODE = c.ACTION_CODE
  JOIN sig s ON s.CUSTOMER_ID = c.CUSTOMER_ID AND s.SIGNAL_NAME = g.SIGNAL_NAME
  WHERE CASE g.OPERATOR WHEN '>=' THEN s.SIGNAL_VALUE >= g.THRESHOLD WHEN '<' THEN s.SIGNAL_VALUE < g.THRESHOLD
                        WHEN '<=' THEN s.SIGNAL_VALUE <= g.THRESHOLD WHEN '>' THEN s.SIGNAL_VALUE > g.THRESHOLD END
  GROUP BY 1, 2),
offer AS (
  SELECT c.CUSTOMER_ID, c.ACTION_CODE,
    ARRAY_AGG(IFF(e.IS_ELIGIBLE, OBJECT_CONSTRUCT('offer_id', e.OFFER_ID, 'offer_name', e.OFFER_NAME, 'policy_doc', e.POLICY_DOC_ID,
              'passed_rules', e.PASSED_RULES), NULL)) WITHIN GROUP (ORDER BY e.PRIORITY DESC) ELIGIBLE_OFFERS,
    ARRAY_AGG(IFF(NOT e.IS_ELIGIBLE, OBJECT_CONSTRUCT('offer_id', e.OFFER_ID, 'offer_name', e.OFFER_NAME, 'failed_rules', e.FAILED_RULES), NULL))
      WITHIN GROUP (ORDER BY e.PRIORITY DESC) INELIGIBLE_OFFERS
  FROM cand c JOIN OFFER_ELIGIBILITY e ON e.CUSTOMER_ID = c.CUSTOMER_ID AND e.OFFER_CATEGORY = c.OFFER_CATEGORY
  GROUP BY 1, 2),
j AS (
  SELECT c.CUSTOMER_ID, c.ACTION_CODE, c.ACTION_NAME, c.OFFER_CATEGORY, c.OFFER_MODE, c.BUSINESS_PURPOSE, c.OWNER_ROLE, c.DEFAULT_CHANNEL,
    ROUND(s.SCORE, 4) ACTION_SCORE, ARRAY_SLICE(s.CONTRIBUTIONS, 0, 4) TOP_CONTRIBUTIONS,
    COALESCE(g.BLOCK_REASONS, []) BLOCK_REASONS,
    o.ELIGIBLE_OFFERS[0] SELECTED_OFFER, COALESCE(o.INELIGIBLE_OFFERS, []) INELIGIBLE_OFFERS,
    CASE WHEN ARRAY_SIZE(COALESCE(g.BLOCK_REASONS, [])) > 0 THEN 'BLOCKED_GUARDRAIL'
         WHEN c.OFFER_MODE = 'REQUIRED' AND o.ELIGIBLE_OFFERS[0] IS NULL THEN 'NOT_ELIGIBLE'
         WHEN c.ACTION_CODE <> 'NO_ACTION_MONITOR' AND s.SCORE < m.MIN_SCORE THEN 'BELOW_THRESHOLD'
         ELSE 'ELIGIBLE' END CANDIDATE_STATUS
  FROM cand c JOIN scored s USING (CUSTOMER_ID, ACTION_CODE)
  CROSS JOIN (SELECT COALESCE(MAX(IFF(CONFIG_KEY = 'MIN_ACTION_SCORE', TRY_TO_DOUBLE(CONFIG_VALUE), NULL)), 0.40) MIN_SCORE FROM APP_CONFIG) m
  LEFT JOIN guard g USING (CUSTOMER_ID, ACTION_CODE) LEFT JOIN offer o USING (CUSTOMER_ID, ACTION_CODE))
SELECT j.*,
  IFF(CANDIDATE_STATUS = 'ELIGIBLE', ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID, CANDIDATE_STATUS = 'ELIGIBLE' ORDER BY ACTION_SCORE DESC, ACTION_CODE), NULL) ELIGIBLE_RANK
FROM j;

-- ---------------------------------------------------------------------
-- CUSTOMER_360  (one row per customer; the single source for UI + agent)
-- ---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE CUSTOMER_360
  TARGET_LAG = '12 hours' WAREHOUSE = ACTION360_WH REFRESH_MODE = FULL
  COMMENT = 'Unified Customer 360: identity, financial, interaction, risk, AI context and recommended action'
AS
WITH top2 AS (
  SELECT CUSTOMER_ID,
    MAX(IFF(ELIGIBLE_RANK = 1, ACTION_CODE, NULL)) RECOMMENDED_ACTION,
    MAX(IFF(ELIGIBLE_RANK = 1, ACTION_NAME, NULL)) RECOMMENDED_ACTION_NAME,
    MAX(IFF(ELIGIBLE_RANK = 1, ACTION_SCORE, NULL)) RECOMMENDED_ACTION_SCORE,
    MAX(IFF(ELIGIBLE_RANK = 1, SELECTED_OFFER:offer_id::STRING, NULL)) RECOMMENDED_OFFER_ID,
    MAX(IFF(ELIGIBLE_RANK = 2, ACTION_CODE, NULL)) SECONDARY_ACTION,
    MAX(IFF(ELIGIBLE_RANK = 2, ACTION_SCORE, NULL)) SECONDARY_ACTION_SCORE,
    COUNT_IF(CANDIDATE_STATUS = 'ELIGIBLE' AND ACTION_CODE <> 'NO_ACTION_MONITOR') ELIGIBLE_ACTION_COUNT
  FROM NBA_CANDIDATE GROUP BY 1),
latest AS (
  SELECT i.CUSTOMER_ID,
    ARRAY_AGG(OBJECT_CONSTRUCT('ts', i.INTERACTION_TS, 'channel', i.CHANNEL, 'topic', i.TOPIC, 'note', i.NOTE))
      WITHIN GROUP (ORDER BY COALESCE(t.AI_SENTIMENT_SCORE, i.RULE_SENTIMENT), i.INTERACTION_TS DESC)[0] LATEST_IMPORTANT_INTERACTION
  FROM FACT_INTERACTION i LEFT JOIN CALL_TRANSCRIPT t USING (INTERACTION_ID)
  WHERE i.INTERACTION_TS >= DATEADD(day, -120, '2026-10-02'::DATE)
  GROUP BY 1)
SELECT f.CUSTOMER_ID, f.FULL_NAME, f.SEGMENT, f.INDUSTRY_TYPE, f.AGE, f.CITY, f.TENURE_MONTHS, f.PREFERRED_CHANNEL, f.CREDIT_SCORE,
  f.PRODUCT_COUNT, f.PRODUCTS, f.TOTAL_OUTSTANDING, f.TOTAL_EXPOSURE_OR_COVER, f.MONTHLY_OBLIGATION, f.OVERDUE_AMOUNT,
  f.PAYMENT_STATUS, f.MISSED_6M, f.LATE_6M, f.MAX_DAYS_LATE_90D, f.ON_TIME_RATE_12M,
  f.NEXT_RENEWAL_DATE, f.NEXT_RENEWAL_PRODUCT, f.DAYS_TO_RENEWAL, f.ANNUAL_VALUE_INR, ROUND(f.VALUE_PERCENTILE, 3) VALUE_PERCENTILE,
  f.TOTAL_INTERACTIONS, f.INTERACTIONS_90D, f.COMPLAINTS_90D, f.UNRESOLVED_COUNT, f.OPEN_REQUESTS, f.ESCALATED_COUNT, f.NEGATIVE_INTERACTIONS_90D,
  f.AVG_SENTIMENT_90D, f.LATEST_SENTIMENT,
  CASE WHEN f.AVG_SENTIMENT_90D IS NULL THEN 'NO RECENT CONTACT' WHEN f.AVG_SENTIMENT_90D <= -0.3 THEN 'NEGATIVE'
       WHEN f.AVG_SENTIMENT_90D < 0.1 THEN 'NEUTRAL' ELSE 'POSITIVE' END SENTIMENT_LABEL,
  f.DOMINANT_TOPIC, f.LAST_INTERACTION_TS, f.DAYS_SINCE_LAST_INTERACTION,
  f.COMPETITOR_MENTION, f.LIFE_EVENT, f.HARDSHIP_MENTION, f.FORECLOSURE_FLAG, f.CLAIM_DELAYED_FLAG, f.CLAIMS_12M,
  r.CHURN_RISK, r.PAYMENT_RISK, r.SERVICE_RISK, r.OPPORTUNITY_SCORE, r.RISK_SCORE, r.RISK_TIER, r.PRIMARY_RISK_TYPE, r.AI_ROUTE, r.TOP_DRIVERS,
  t.RECOMMENDED_ACTION, t.RECOMMENDED_ACTION_NAME, t.RECOMMENDED_ACTION_SCORE, t.RECOMMENDED_OFFER_ID,
  t.SECONDARY_ACTION, t.SECONDARY_ACTION_SCORE, t.ELIGIBLE_ACTION_COUNT,
  IFF(t.RECOMMENDED_ACTION <> 'NO_ACTION_MONITOR', TRUE, FALSE) NEEDS_ACTION,
  ai.CUSTOMER_NEED, ai.KEY_DRIVERS AI_KEY_DRIVERS, ai.PAIN_POINTS AI_PAIN_POINTS, ai.GENERATED_AT AI_GENERATED_AT,
  l.LATEST_IMPORTANT_INTERACTION
FROM CUSTOMER_FEATURES f
JOIN CUSTOMER_RISK r USING (CUSTOMER_ID)
LEFT JOIN top2 t USING (CUSTOMER_ID)
LEFT JOIN CUSTOMER_AI_INSIGHT ai USING (CUSTOMER_ID)
LEFT JOIN latest l USING (CUSTOMER_ID);

-- ---------------------------------------------------------------------
-- Persisted recommendations, immutable audit, AI usage, evaluation
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS NBA_RECOMMENDATION (
  RECOMMENDATION_ID STRING DEFAULT UUID_STRING() PRIMARY KEY, CUSTOMER_ID STRING, QUESTION STRING,
  SELECTED_ACTION STRING, CANDIDATE_ACTIONS VARIANT, ACTION_SCORE FLOAT, REASONS VARIANT, SUPPORTING_EVIDENCE VARIANT,
  OFFER_ID STRING, ELIGIBILITY_RESULT VARIANT, CONFIDENCE STRING, AI_ROUTE STRING, GENERATED_EXPLANATION STRING,
  GENERATED_MESSAGE STRING, MODEL STRING, LATENCY_MS INT, CREATED_BY STRING DEFAULT CURRENT_USER(),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE TABLE IF NOT EXISTS ACTION_AUDIT (
  AUDIT_ID STRING DEFAULT UUID_STRING() PRIMARY KEY, RECOMMENDATION_ID STRING, CUSTOMER_ID STRING, QUESTION STRING,
  RECOMMENDATION STRING, RECOMMENDATION_REASON STRING, OFFER_ID STRING, ELIGIBILITY_STATUS STRING, EVIDENCE_REFERENCES VARIANT,
  USER_ACTION STRING, OUTREACH_MESSAGE STRING, EXECUTION_MODE STRING DEFAULT 'SIMULATED', DOWNSTREAM_STATUS STRING,
  ACTED_BY STRING DEFAULT CURRENT_USER(), ACTED_ROLE STRING DEFAULT CURRENT_ROLE(),
  ACTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PREV_HASH STRING, RECORD_HASH STRING)
  CHANGE_TRACKING = TRUE
  COMMENT = 'Append-only audit. Writes only via CORE.LOG_ACTION; hash chain makes tampering detectable';

CREATE TABLE IF NOT EXISTS AI_USAGE_METRICS (
  EVENT_ID STRING DEFAULT UUID_STRING(), EVENT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), COMPONENT STRING,
  CUSTOMER_ID STRING, AI_ROUTE STRING, AI_FUNCTION STRING, MODEL STRING, CALLS INT, EST_TOKENS INT, LATENCY_MS INT,
  SKIPPED BOOLEAN DEFAULT FALSE, DETAILS VARIANT);

CREATE TABLE IF NOT EXISTS EVALUATION_CASE (
  CASE_ID STRING PRIMARY KEY, SCENARIO STRING, CUSTOMER_ID STRING, QUESTION STRING, EXPECTED_ACTION STRING,
  EXPECTED_OFFER_ID STRING, EXPECTED_ELIGIBILITY STRING, FORBIDDEN_OFFER_ID STRING, EXPECTED_ROUTE STRING,
  MUST_CITE STRING, IS_NEGATIVE BOOLEAN);
