-- =====================================================================
-- ACTION360 :: AI pipeline run (cost-routed). Safe to re-run: only un-enriched rows are processed.
-- =====================================================================
USE WAREHOUSE ACTION360_WH;
USE SCHEMA ACTION360_DB.CORE;
CALL CORE.INGEST_CALL_AUDIO();
CALL CORE.ENRICH_TRANSCRIPTS(5000);
ALTER DYNAMIC TABLE CORE.CUSTOMER_360 REFRESH;
CALL CORE.GENERATE_CUSTOMER_INSIGHTS(1, 'C10238');
CALL CORE.GENERATE_CUSTOMER_INSIGHTS(1, 'C10417');
CALL CORE.GENERATE_CUSTOMER_INSIGHTS(1, 'C10555');
CALL CORE.GENERATE_CUSTOMER_INSIGHTS(1, 'C10789');
CALL CORE.GENERATE_CUSTOMER_INSIGHTS(1, 'C11024');
CALL CORE.GENERATE_CUSTOMER_INSIGHTS(100, NULL);
ALTER DYNAMIC TABLE CORE.CUSTOMER_360 REFRESH;
