-- =====================================================================
-- ACTION360 :: 04 Customer Signal Engine
--   CUSTOMER_FEATURES (DT)  raw behavioural features from structured + unstructured data
--   SIGNAL_DEFINITION       governed catalogue of normalised signals
--   CUSTOMER_SIGNAL   (DT)  long-format normalised signals in [0,1]
--   RISK_MODEL_WEIGHT       configurable weights (no hard-coded scoring in app code)
--   CUSTOMER_RISK     (DT)  churn / payment / service risk + explainable top drivers + AI route
-- Everything here is deterministic. AI only *contributes* (sentiment / intent) via
-- CALL_TRANSCRIPT AI_* columns populated by the cost-aware enrichment task.
-- =====================================================================
USE WAREHOUSE ACTION360_WH;
USE SCHEMA ACTION360_DB.CORE;

-- AI insight store (only populated for customers routed to FULL enrichment)
CREATE TABLE IF NOT EXISTS CUSTOMER_AI_INSIGHT (
  CUSTOMER_ID STRING PRIMARY KEY, CUSTOMER_NEED STRING, KEY_DRIVERS VARIANT, PAIN_POINTS VARIANT,
  LATEST_IMPORTANT_INTERACTION STRING, MODEL STRING, GENERATED_AT TIMESTAMP_NTZ);

-- ---------------------------------------------------------------------
-- CUSTOMER_FEATURES
-- ---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE CUSTOMER_FEATURES
  TARGET_LAG = 'DOWNSTREAM' WAREHOUSE = ACTION360_WH REFRESH_MODE = FULL
  COMMENT = 'Per-customer behavioural features (structured + transcript-derived)'
AS
WITH cfg AS (SELECT TO_DATE(CONFIG_VALUE) AS AS_OF FROM APP_CONFIG WHERE CONFIG_KEY = 'AS_OF_DATE'),
acc AS (
  SELECT CUSTOMER_ID, COUNT(*) PRODUCT_COUNT, ARRAY_AGG(DISTINCT PRODUCT_CODE) WITHIN GROUP (ORDER BY PRODUCT_CODE) PRODUCTS,
    SUM(OUTSTANDING_BALANCE) TOTAL_OUTSTANDING, SUM(PRINCIPAL_OR_SUM_ASSURED) TOTAL_EXPOSURE_OR_COVER,
    SUM(MONTHLY_INSTALMENT) MONTHLY_OBLIGATION, MIN(RENEWAL_OR_RESET_DATE) NEXT_RENEWAL_DATE,
    MIN_BY(PRODUCT_CODE, RENEWAL_OR_RESET_DATE) NEXT_RENEWAL_PRODUCT,
    MAX(IFF(PRODUCT_CODE = 'HL', 1, 0)) HAS_HL, MAX(IFF(PRODUCT_CODE = 'PL', 1, 0)) HAS_PL, MAX(IFF(PRODUCT_CODE = 'AL', 1, 0)) HAS_AL,
    MAX(IFF(PRODUCT_CODE = 'CC', 1, 0)) HAS_CC, MAX(IFF(PRODUCT_CODE = 'HEALTH', 1, 0)) HAS_HEALTH,
    MAX(IFF(PRODUCT_CODE = 'FAMILY_FLOATER', 1, 0)) HAS_FAMILY_FLOATER, MAX(IFF(PRODUCT_CODE = 'TERM_LIFE', 1, 0)) HAS_TERM_LIFE,
    MAX(IFF(PRODUCT_CODE = 'MOTOR', 1, 0)) HAS_MOTOR, MAX(IFF(PRODUCT_CODE = 'HOME_INS', 1, 0)) HAS_HOME_INS
  FROM FACT_ACCOUNT WHERE STATUS = 'ACTIVE' GROUP BY 1),
pay AS (
  SELECT p.CUSTOMER_ID,
    COUNT_IF(PAYMENT_STATUS IN ('MISSED','PARTIAL') AND DUE_DATE >= DATEADD(month, -6, AS_OF)) MISSED_6M,
    COUNT_IF(PAYMENT_STATUS = 'LATE' AND DUE_DATE >= DATEADD(month, -6, AS_OF)) LATE_6M,
    COALESCE(MAX(IFF(DUE_DATE >= DATEADD(day, -90, AS_OF), DAYS_LATE, NULL)), 0) MAX_DAYS_LATE_90D,
    ROUND(COUNT_IF(PAYMENT_STATUS = 'ON_TIME') / NULLIF(COUNT(*), 0), 3) ON_TIME_RATE_12M,
    SUM(IFF(DUE_DATE >= DATEADD(month, -3, AS_OF), AMOUNT_DUE - AMOUNT_PAID, 0)) OVERDUE_AMOUNT
  FROM FACT_PAYMENT p, cfg GROUP BY 1),
ix AS (
  SELECT i.CUSTOMER_ID, i.INTERACTION_TS, i.TOPIC, i.IS_COMPLAINT, i.RESOLUTION_STATUS, i.CHANNEL,
    COALESCE(t.AI_SENTIMENT_SCORE, i.RULE_SENTIMENT) SENTIMENT, t.AI_INTENT,
    LOWER(COALESCE(t.TRANSCRIPT_TEXT, '') || ' ' || COALESCE(i.NOTE, '')) TXT,
    DATEDIFF(day, i.INTERACTION_TS, cfg.AS_OF) DAYS_AGO
  FROM FACT_INTERACTION i LEFT JOIN CALL_TRANSCRIPT t USING (INTERACTION_ID), cfg),
inter AS (
  SELECT CUSTOMER_ID, COUNT(*) TOTAL_INTERACTIONS, COUNT_IF(DAYS_AGO <= 90) INTERACTIONS_90D,
    COUNT_IF(IS_COMPLAINT AND DAYS_AGO <= 90) COMPLAINTS_90D,
    COUNT_IF(IS_COMPLAINT AND RESOLUTION_STATUS IN ('OPEN','ESCALATED')) UNRESOLVED_COUNT,
    COUNT_IF(NOT IS_COMPLAINT AND RESOLUTION_STATUS = 'OPEN') OPEN_REQUESTS,
    COUNT_IF(RESOLUTION_STATUS = 'ESCALATED') ESCALATED_COUNT,
    COUNT_IF(SENTIMENT <= -0.3 AND DAYS_AGO <= 90) NEGATIVE_INTERACTIONS_90D,
    ROUND(AVG(IFF(DAYS_AGO <= 90, SENTIMENT, NULL)), 3) AVG_SENTIMENT_90D,
    MAX_BY(SENTIMENT, INTERACTION_TS) LATEST_SENTIMENT,
    MAX(INTERACTION_TS) LAST_INTERACTION_TS, MIN(DAYS_AGO) DAYS_SINCE_LAST_INTERACTION,
    MODE(TOPIC) DOMINANT_TOPIC,
    MAX(IFF(DAYS_AGO <= 120 AND (AI_INTENT = 'churn_or_switch_intent' OR TXT ILIKE ANY ('%another bank%','%other bank%','%another insurer%','%balance transfer%','%switch%','%move my%','%move everything%','%cheaper%')), 1, 0)) COMPETITOR_MENTION,
    MAX(IFF(DAYS_AGO <= 180 AND TXT ILIKE ANY ('%baby%','%newborn%','%got married%','%recently married%','%new home%'), 1, 0)) LIFE_EVENT,
    MAX(IFF(DAYS_AGO <= 120 AND (AI_INTENT = 'payment_hardship' OR TXT ILIKE ANY ('%lost my job%','%job loss%','%between jobs%','%money is tight%','%hospital bills%')), 1, 0)) HARDSHIP_MENTION,
    MAX(IFF(DAYS_AGO <= 120 AND (AI_INTENT = 'product_interest_upgrade' OR TXT ILIKE ANY ('%premium%card%','%better travel%','%increase the cover%','%promotion%','%promoted%')), 1, 0)) UPGRADE_INTEREST
  FROM ix GROUP BY 1),
ev AS (
  SELECT e.CUSTOMER_ID,
    MAX(IFF(EVENT_TYPE IN ('FORECLOSURE_ENQUIRY','CANCELLATION_ENQUIRY') AND EVENT_STATUS = 'OPEN', 1, 0)) FORECLOSURE_FLAG,
    MAX(IFF(EVENT_TYPE IN ('RESTRUCTURE_REQUEST','PREMIUM_DEFERRAL_REQUEST') AND EVENT_STATUS = 'OPEN', 1, 0)) RESTRUCTURE_FLAG,
    MAX(IFF(EVENT_TYPE = 'TOPUP_ENQUIRY' AND EVENT_STATUS = 'OPEN', 1, 0)) TOPUP_FLAG,
    MAX(IFF(EVENT_TYPE = 'CLAIM_DELAYED' AND EVENT_STATUS = 'OPEN', 1, 0)) CLAIM_DELAYED_FLAG,
    MAX(IFF(EVENT_TYPE = 'DOCUMENT_PENDING' AND EVENT_STATUS = 'OPEN', 1, 0)) DOC_PENDING_FLAG,
    MAX(IFF(EVENT_TYPE = 'ENDORSEMENT_REQUEST' AND EVENT_STATUS = 'OPEN', 1, 0)) ENDORSEMENT_FLAG,
    MAX(IFF(EVENT_TYPE = 'FEE_DISPUTE' AND EVENT_STATUS = 'OPEN', 1, 0)) FEE_DISPUTE_FLAG,
    COUNT_IF(EVENT_TYPE LIKE 'CLAIM%' AND EVENT_DATE >= DATEADD(month, -12, AS_OF)) CLAIMS_12M
  FROM FACT_CLAIM_OR_LOAN_EVENT e, cfg GROUP BY 1),
tx AS (
  SELECT t.CUSTOMER_ID,
    COUNT_IF(CATEGORY = 'SALARY_CREDIT' AND TXN_DATE >= DATEADD(day, -60, AS_OF)) SALARY_CREDITS_60D,
    COUNT_IF(CATEGORY = 'SALARY_CREDIT' AND TXN_DATE < DATEADD(day, -60, AS_OF)) SALARY_CREDITS_PRIOR,
    SUM(IFF(CATEGORY = 'CARD_SPEND' AND TXN_DATE >= DATEADD(day, -90, AS_OF), AMOUNT, 0)) CARD_SPEND_3M,
    SUM(IFF(CATEGORY = 'CARD_SPEND' AND TXN_DATE < DATEADD(day, -90, AS_OF), AMOUNT, 0)) CARD_SPEND_PREV_3M,
    SUM(IFF(CATEGORY = 'TRANSFER_TO_OTHER_BANK' AND TXN_DATE >= DATEADD(day, -90, AS_OF), AMOUNT, 0)) OUTFLOW_3M,
    SUM(IFF(CATEGORY = 'SALARY_CREDIT' AND TXN_DATE >= DATEADD(day, -90, AS_OF), AMOUNT, 0)) INFLOW_3M
  FROM FACT_TRANSACTION t, cfg GROUP BY 1)
SELECT c.CUSTOMER_ID, c.FULL_NAME, c.SEGMENT, c.INDUSTRY_TYPE, c.AGE, c.CITY, c.TENURE_MONTHS, c.PREFERRED_CHANNEL, c.CREDIT_SCORE, c.MONTHLY_INCOME,
  acc.PRODUCT_COUNT, acc.PRODUCTS, acc.TOTAL_OUTSTANDING, acc.TOTAL_EXPOSURE_OR_COVER, acc.MONTHLY_OBLIGATION,
  acc.NEXT_RENEWAL_DATE, acc.NEXT_RENEWAL_PRODUCT, DATEDIFF(day, cfg.AS_OF, acc.NEXT_RENEWAL_DATE) DAYS_TO_RENEWAL,
  acc.HAS_HL, acc.HAS_PL, acc.HAS_AL, acc.HAS_CC, acc.HAS_HEALTH, acc.HAS_FAMILY_FLOATER, acc.HAS_TERM_LIFE, acc.HAS_MOTOR, acc.HAS_HOME_INS,
  COALESCE(pay.MISSED_6M, 0) MISSED_6M, COALESCE(pay.LATE_6M, 0) LATE_6M, COALESCE(pay.MAX_DAYS_LATE_90D, 0) MAX_DAYS_LATE_90D,
  pay.ON_TIME_RATE_12M, COALESCE(pay.OVERDUE_AMOUNT, 0) OVERDUE_AMOUNT,
  CASE WHEN COALESCE(pay.MISSED_6M, 0) > 0 THEN 'DELINQUENT' WHEN COALESCE(pay.LATE_6M, 0) > 0 THEN 'OCCASIONALLY_LATE' ELSE 'CURRENT' END PAYMENT_STATUS,
  COALESCE(inter.TOTAL_INTERACTIONS, 0) TOTAL_INTERACTIONS, COALESCE(inter.INTERACTIONS_90D, 0) INTERACTIONS_90D,
  COALESCE(inter.COMPLAINTS_90D, 0) COMPLAINTS_90D, COALESCE(inter.UNRESOLVED_COUNT, 0) UNRESOLVED_COUNT, COALESCE(inter.OPEN_REQUESTS, 0) OPEN_REQUESTS,
  COALESCE(inter.ESCALATED_COUNT, 0) ESCALATED_COUNT, COALESCE(inter.NEGATIVE_INTERACTIONS_90D, 0) NEGATIVE_INTERACTIONS_90D,
  inter.AVG_SENTIMENT_90D, inter.LATEST_SENTIMENT, inter.LAST_INTERACTION_TS, inter.DAYS_SINCE_LAST_INTERACTION, inter.DOMINANT_TOPIC,
  COALESCE(inter.COMPETITOR_MENTION, 0) COMPETITOR_MENTION, COALESCE(inter.LIFE_EVENT, 0) LIFE_EVENT,
  COALESCE(inter.HARDSHIP_MENTION, 0) HARDSHIP_MENTION, COALESCE(inter.UPGRADE_INTEREST, 0) UPGRADE_INTEREST,
  COALESCE(ev.FORECLOSURE_FLAG, 0) FORECLOSURE_FLAG, COALESCE(ev.RESTRUCTURE_FLAG, 0) RESTRUCTURE_FLAG, COALESCE(ev.TOPUP_FLAG, 0) TOPUP_FLAG,
  COALESCE(ev.CLAIM_DELAYED_FLAG, 0) CLAIM_DELAYED_FLAG, COALESCE(ev.DOC_PENDING_FLAG, 0) DOC_PENDING_FLAG,
  COALESCE(ev.ENDORSEMENT_FLAG, 0) ENDORSEMENT_FLAG, COALESCE(ev.FEE_DISPUTE_FLAG, 0) FEE_DISPUTE_FLAG, COALESCE(ev.CLAIMS_12M, 0) CLAIMS_12M,
  IFF(tx.SALARY_CREDITS_PRIOR > 0 AND tx.SALARY_CREDITS_60D = 0, 1, 0) SALARY_DROP_FLAG,
  ROUND(DIV0NULL(tx.CARD_SPEND_3M, tx.CARD_SPEND_PREV_3M), 3) SPEND_TREND,
  ROUND(DIV0NULL(tx.OUTFLOW_3M, tx.INFLOW_3M), 3) OUTFLOW_RATIO,
  -- Annual relationship value proxy (net interest margin + fee/premium income)
  ROUND(COALESCE(acc.TOTAL_OUTSTANDING, 0) * 0.025 + COALESCE(acc.MONTHLY_OBLIGATION, 0) * 12 * IFF(c.INDUSTRY_TYPE = 'INSURANCE', 0.25, 0.05)
        + DECODE(c.SEGMENT, 'PREMIER', 60000, 'AFFLUENT', 20000, 'SME', 25000, 5000), 0) ANNUAL_VALUE_INR,
  PERCENT_RANK() OVER (ORDER BY ANNUAL_VALUE_INR) VALUE_PERCENTILE
FROM DIM_CUSTOMER c CROSS JOIN cfg
LEFT JOIN acc USING (CUSTOMER_ID) LEFT JOIN pay USING (CUSTOMER_ID) LEFT JOIN inter USING (CUSTOMER_ID)
LEFT JOIN ev USING (CUSTOMER_ID) LEFT JOIN tx USING (CUSTOMER_ID);

-- ---------------------------------------------------------------------
-- Signal catalogue (governed definitions shown in the UI and to the agent)
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE SIGNAL_DEFINITION (SIGNAL_NAME STRING PRIMARY KEY, DISPLAY_NAME STRING, SIGNAL_SOURCE STRING, DEFINITION STRING);
INSERT INTO SIGNAL_DEFINITION VALUES
 ('NEG_SENTIMENT','Negative sentiment (90d)','AI+RULE','max(0, -average sentiment of last-90-day interactions); AI_SENTIMENT overrides rule baseline when enriched'),
 ('COMPLAINTS','Complaint frequency (90d)','RULE','complaints in last 90 days, capped at 3'),
 ('UNRESOLVED','Unresolved complaints','RULE','open or escalated complaints, capped at 2'),
 ('ESCALATED','Escalated complaint','RULE','1 if any interaction is escalated'),
 ('RENEWAL_PROXIMITY','Renewal / rate-reset proximity','RULE','1 - days_to_renewal/90 when within 90 days'),
 ('MISSED_PAYMENTS','Missed / partial payments (6m)','RULE','missed or partial instalments in 6 months, capped at 3'),
 ('DAYS_LATE','Days past due (90d)','RULE','max days late in 90 days, capped at 60'),
 ('SALARY_DROP','Salary credits stopped','RULE','salary credits present before but none in last 60 days'),
 ('HARDSHIP','Hardship stated','AI+RULE','customer stated job loss / medical / money is tight'),
 ('RESTRUCTURE_REQ','Restructure / deferral requested','RULE','open restructure or premium-deferral request'),
 ('LOW_CREDIT','Low credit quality','RULE','(750 - credit score)/200 clipped to [0,1]'),
 ('FORECLOSURE_INTENT','Foreclosure / cancellation enquiry','RULE','open foreclosure or cancellation enquiry'),
 ('COMPETITOR_MENTION','Competitor / switching intent','AI+RULE','switching language or AI intent churn_or_switch_intent in last 120 days'),
 ('OUTFLOW_OTHER_BANK','Funds moving out','RULE','transfers to other banks / salary inflow (3m), capped at 1'),
 ('LOW_TENURE','New relationship','RULE','tenure below 12 months'),
 ('CUSTOMER_VALUE','Customer value','RULE','percentile of annual relationship value'),
 ('ENGAGEMENT','Engagement (90d)','RULE','interactions in last 90 days, capped at 5'),
 ('RECENCY','Recent contact','RULE','1 - days since last interaction / 90'),
 ('PRODUCT_GAP','Product / coverage gap','RULE','insurance: no term life or individual-only health; lending: affluent+ with a single product'),
 ('LIFE_EVENT','Life event detected','AI+RULE','newborn, marriage or new home mentioned in last 180 days'),
 ('UPGRADE_READINESS','Upgrade readiness','RULE','spend growth, upgrade interest and clean repayment'),
 ('CREDIT_QUALITY','Credit quality','RULE','(credit score - 550)/300 clipped to [0,1]'),
 ('CLAIM_DELAYED','Delayed claim','RULE','open claim beyond SLA'),
 ('DOC_PENDING','Document pending','RULE','open document request'),
 ('TOPUP_INTENT','Top-up / limit enquiry','RULE','open top-up enquiry');

-- ---------------------------------------------------------------------
-- CUSTOMER_SIGNAL  (normalised, long format)
-- ---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE CUSTOMER_SIGNAL
  TARGET_LAG = 'DOWNSTREAM' WAREHOUSE = ACTION360_WH REFRESH_MODE = FULL
  COMMENT = 'Normalised customer signals in [0,1]'
AS
WITH n AS (
  SELECT CUSTOMER_ID,
    GREATEST(0, -COALESCE(AVG_SENTIMENT_90D, 0))::FLOAT NEG_SENTIMENT,
    LEAST(COMPLAINTS_90D, 3) / 3.0::FLOAT COMPLAINTS,
    LEAST(UNRESOLVED_COUNT, 2) / 2.0::FLOAT UNRESOLVED,
    IFF(ESCALATED_COUNT > 0, 1, 0)::FLOAT ESCALATED,
    IFF(DAYS_TO_RENEWAL BETWEEN 0 AND 90, 1 - DAYS_TO_RENEWAL / 90.0, 0)::FLOAT RENEWAL_PROXIMITY,
    LEAST(MISSED_6M, 3) / 3.0::FLOAT MISSED_PAYMENTS,
    LEAST(MAX_DAYS_LATE_90D, 60) / 60.0::FLOAT DAYS_LATE,
    SALARY_DROP_FLAG::FLOAT SALARY_DROP,
    HARDSHIP_MENTION::FLOAT HARDSHIP,
    RESTRUCTURE_FLAG::FLOAT RESTRUCTURE_REQ,
    LEAST(1, GREATEST(0, (750 - CREDIT_SCORE) / 200.0))::FLOAT LOW_CREDIT,
    FORECLOSURE_FLAG::FLOAT FORECLOSURE_INTENT,
    COMPETITOR_MENTION::FLOAT COMPETITOR_MENTION,
    LEAST(1, COALESCE(OUTFLOW_RATIO, 0) * 2)::FLOAT OUTFLOW_OTHER_BANK,
    IFF(TENURE_MONTHS < 12, 1, 0)::FLOAT LOW_TENURE,
    VALUE_PERCENTILE::FLOAT CUSTOMER_VALUE,
    LEAST(INTERACTIONS_90D, 5) / 5.0::FLOAT ENGAGEMENT,
    IFF(DAYS_SINCE_LAST_INTERACTION IS NULL, 0, GREATEST(0, 1 - DAYS_SINCE_LAST_INTERACTION / 90.0))::FLOAT RECENCY,
    IFF(INDUSTRY_TYPE = 'INSURANCE', IFF(HAS_TERM_LIFE = 0, 0.5, 0) + IFF(HAS_HEALTH = 1 AND HAS_FAMILY_FLOATER = 0, 0.5, 0) * IFF(LIFE_EVENT = 1 OR ENDORSEMENT_FLAG = 1, 1, 0.4),
        IFF(SEGMENT IN ('AFFLUENT','PREMIER') AND PRODUCT_COUNT = 1, 0.6, 0))::FLOAT PRODUCT_GAP,
    GREATEST(LIFE_EVENT, ENDORSEMENT_FLAG)::FLOAT LIFE_EVENT,
    LEAST(1, 0.4 * LEAST(1, GREATEST(0, (COALESCE(SPEND_TREND, 1) - 1) * 2.5)) + 0.4 * UPGRADE_INTEREST + 0.2 * IFF(MISSED_6M = 0 AND LATE_6M = 0, 1, 0))::FLOAT UPGRADE_READINESS,
    LEAST(1, GREATEST(0, (CREDIT_SCORE - 550) / 300.0))::FLOAT CREDIT_QUALITY,
    CLAIM_DELAYED_FLAG::FLOAT CLAIM_DELAYED,
    DOC_PENDING_FLAG::FLOAT DOC_PENDING,
    TOPUP_FLAG::FLOAT TOPUP_INTENT
  FROM CUSTOMER_FEATURES),
o AS (SELECT CUSTOMER_ID, OBJECT_CONSTRUCT(*) OBJ FROM n)
SELECT o.CUSTOMER_ID, f.KEY::STRING SIGNAL_NAME, ROUND(f.VALUE::FLOAT, 4) SIGNAL_VALUE, d.DISPLAY_NAME, d.SIGNAL_SOURCE
FROM o, LATERAL FLATTEN(INPUT => o.OBJ) f
-- the join to the governed catalogue keeps only defined signals (drops CUSTOMER_ID)
JOIN SIGNAL_DEFINITION d ON d.SIGNAL_NAME = f.KEY::STRING;

-- ---------------------------------------------------------------------
-- Configurable risk model weights (each model sums to 1.0)
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE RISK_MODEL_WEIGHT (RISK_MODEL STRING, SIGNAL_NAME STRING, WEIGHT FLOAT, PRIMARY KEY (RISK_MODEL, SIGNAL_NAME));
INSERT INTO RISK_MODEL_WEIGHT VALUES
 ('CHURN','NEG_SENTIMENT',0.17),('CHURN','COMPLAINTS',0.13),('CHURN','UNRESOLVED',0.12),('CHURN','FORECLOSURE_INTENT',0.14),
 ('CHURN','COMPETITOR_MENTION',0.14),('CHURN','RENEWAL_PROXIMITY',0.10),('CHURN','OUTFLOW_OTHER_BANK',0.08),('CHURN','LOW_TENURE',0.05),('CHURN','ESCALATED',0.07),
 ('PAYMENT','MISSED_PAYMENTS',0.32),('PAYMENT','DAYS_LATE',0.22),('PAYMENT','SALARY_DROP',0.16),('PAYMENT','HARDSHIP',0.12),('PAYMENT','RESTRUCTURE_REQ',0.10),('PAYMENT','LOW_CREDIT',0.08),
 ('SERVICE','UNRESOLVED',0.33),('SERVICE','COMPLAINTS',0.25),('SERVICE','ESCALATED',0.15),('SERVICE','CLAIM_DELAYED',0.15),('SERVICE','NEG_SENTIMENT',0.12);

-- ---------------------------------------------------------------------
-- CUSTOMER_RISK  (scores, tier, explainable drivers, cost-aware AI route)
-- ---------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE CUSTOMER_RISK
  TARGET_LAG = 'DOWNSTREAM' WAREHOUSE = ACTION360_WH REFRESH_MODE = FULL
  COMMENT = 'Churn / payment / service risk with drivers and AI enrichment route'
AS
WITH contrib AS (
  SELECT s.CUSTOMER_ID, w.RISK_MODEL, s.SIGNAL_NAME, s.DISPLAY_NAME, s.SIGNAL_VALUE, w.WEIGHT, s.SIGNAL_VALUE * w.WEIGHT AS CONTRIBUTION
  FROM CUSTOMER_SIGNAL s JOIN RISK_MODEL_WEIGHT w ON w.SIGNAL_NAME = s.SIGNAL_NAME),
agg AS (
  SELECT CUSTOMER_ID,
    ROUND(SUM(IFF(RISK_MODEL = 'CHURN', CONTRIBUTION, 0)), 4) CHURN_RISK,
    ROUND(SUM(IFF(RISK_MODEL = 'PAYMENT', CONTRIBUTION, 0)), 4) PAYMENT_RISK,
    ROUND(SUM(IFF(RISK_MODEL = 'SERVICE', CONTRIBUTION, 0)), 4) SERVICE_RISK
  FROM contrib GROUP BY 1),
-- Opportunity (growth) score: upgrade readiness or a coverage gap backed by a life event
opp AS (
  SELECT CUSTOMER_ID, ROUND(GREATEST(MAX(IFF(SIGNAL_NAME = 'UPGRADE_READINESS', SIGNAL_VALUE, 0)),
         (MAX(IFF(SIGNAL_NAME = 'PRODUCT_GAP', SIGNAL_VALUE, 0)) + MAX(IFF(SIGNAL_NAME = 'LIFE_EVENT', SIGNAL_VALUE, 0))) / 2), 4) OPPORTUNITY_SCORE
  FROM CUSTOMER_SIGNAL GROUP BY 1),
drv AS (
  SELECT CUSTOMER_ID,
    ARRAY_AGG(OBJECT_CONSTRUCT('signal', SIGNAL_NAME, 'label', DISPLAY_NAME, 'model', RISK_MODEL, 'value', SIGNAL_VALUE, 'contribution', ROUND(CONTRIBUTION, 4)))
      WITHIN GROUP (ORDER BY CONTRIBUTION DESC) ALL_DRIVERS
  FROM (SELECT * FROM contrib WHERE CONTRIBUTION > 0
        QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID, SIGNAL_NAME ORDER BY CONTRIBUTION DESC) = 1)
  GROUP BY 1),
th AS (SELECT MAX(IFF(CONFIG_KEY = 'LLM_ENRICHMENT_THRESHOLD', TRY_TO_DOUBLE(CONFIG_VALUE), NULL)) FULL_T,
              MAX(IFF(CONFIG_KEY = 'SELECTIVE_ENRICHMENT_THRESHOLD', TRY_TO_DOUBLE(CONFIG_VALUE), NULL)) SEL_T FROM APP_CONFIG)
SELECT a.CUSTOMER_ID, a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK, opp.OPPORTUNITY_SCORE,
  GREATEST(a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK) RISK_SCORE,
  CASE GREATEST(a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK) WHEN a.CHURN_RISK THEN 'CHURN' WHEN a.PAYMENT_RISK THEN 'PAYMENT' ELSE 'SERVICE' END PRIMARY_RISK_TYPE,
  CASE WHEN GREATEST(a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK) >= th.FULL_T THEN 'HIGH'
       WHEN GREATEST(a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK) >= th.SEL_T THEN 'MEDIUM' ELSE 'LOW' END RISK_TIER,
  CASE WHEN GREATEST(a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK) >= th.FULL_T THEN 'FULL_AGENT'
       WHEN GREATEST(a.CHURN_RISK, a.PAYMENT_RISK, a.SERVICE_RISK) >= th.SEL_T OR opp.OPPORTUNITY_SCORE >= 0.6 THEN 'SELECTIVE_AI' ELSE 'RULES_ONLY' END AI_ROUTE,
  ARRAY_SLICE(COALESCE(d.ALL_DRIVERS, []), 0, 3) TOP_DRIVERS
FROM agg a CROSS JOIN th LEFT JOIN drv d USING (CUSTOMER_ID) LEFT JOIN opp USING (CUSTOMER_ID);
