-- =====================================================================
-- ACTION360 :: 01 Snowflake setup
-- Isolated database, schemas, cost-capped warehouse, stages, roles.
-- Idempotent: safe to re-run.
-- =====================================================================
USE ROLE ACCOUNTADMIN;

-- Dedicated, small, aggressively auto-suspending warehouse
CREATE WAREHOUSE IF NOT EXISTS ACTION360_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE COMMENT = 'ACTION360 hackathon compute (XS, 60s suspend)';

-- Resource monitor: hard cap well below the ~$400 trial budget
CREATE RESOURCE MONITOR IF NOT EXISTS ACTION360_RM WITH CREDIT_QUOTA = 60
  FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY ON 95 PERCENT DO SUSPEND ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE ACTION360_WH SET RESOURCE_MONITOR = ACTION360_RM;

CREATE DATABASE IF NOT EXISTS ACTION360_DB COMMENT = 'ACTION360 Customer 360 & NBA Copilot (synthetic data only)';
CREATE SCHEMA IF NOT EXISTS ACTION360_DB.RAW      COMMENT = 'Landing zone (structured + unstructured)';
CREATE SCHEMA IF NOT EXISTS ACTION360_DB.CORE     COMMENT = 'Curated model, Customer 360, signals, NBA, audit';
CREATE SCHEMA IF NOT EXISTS ACTION360_DB.AI       COMMENT = 'AI functions, search services, agent, semantic view';
CREATE SCHEMA IF NOT EXISTS ACTION360_DB.APP      COMMENT = 'Streamlit application';

USE WAREHOUSE ACTION360_WH;
USE SCHEMA ACTION360_DB.RAW;

-- Stages for unstructured content (server-side encryption required for AI_TRANSCRIBE / directory)
CREATE STAGE IF NOT EXISTS ACTION360_DB.RAW.DOCS_STAGE  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') COMMENT = 'Knowledge documents';
CREATE STAGE IF NOT EXISTS ACTION360_DB.RAW.AUDIO_STAGE DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') COMMENT = 'Call recordings for AI_TRANSCRIBE';
CREATE STAGE IF NOT EXISTS ACTION360_DB.APP.APP_STAGE   DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') COMMENT = 'Streamlit source';

-- Runtime configuration (single source of truth for thresholds, models, weights live in NBA_WEIGHT)
CREATE TABLE IF NOT EXISTS ACTION360_DB.CORE.APP_CONFIG (
  CONFIG_KEY STRING PRIMARY KEY, CONFIG_VALUE STRING, DESCRIPTION STRING,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
MERGE INTO ACTION360_DB.CORE.APP_CONFIG t USING (
  SELECT * FROM VALUES
   ('LLM_ENRICHMENT_THRESHOLD','0.60','Risk score >= this gets full agent/LLM enrichment'),
   ('SELECTIVE_ENRICHMENT_THRESHOLD','0.35','Risk score >= this gets selective (sentiment/search) enrichment'),
   ('PERSONALIZATION_MODEL','claude-sonnet-4-5','Model for personalised outreach'),
   ('LIGHT_MODEL','llama3.1-8b','Cheap model for short summaries'),
   ('ENVIRONMENT','HACKATHON_DEMO','Environment label; downstream actions are SIMULATED'),
   ('EST_CREDITS_PER_LLM_CALL','0.002','Planning estimate used for avoided-cost KPI')
  ) s(k,v,d) ON t.CONFIG_KEY = s.k
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY,CONFIG_VALUE,DESCRIPTION) VALUES (s.k,s.v,s.d);

-- RBAC: least-privilege business role for the app users
CREATE ROLE IF NOT EXISTS ACTION360_ANALYST;
GRANT ROLE ACTION360_ANALYST TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE ACTION360_WH TO ROLE ACTION360_ANALYST;
GRANT USAGE ON DATABASE ACTION360_DB TO ROLE ACTION360_ANALYST;
GRANT USAGE ON SCHEMA ACTION360_DB.CORE TO ROLE ACTION360_ANALYST;
GRANT USAGE ON SCHEMA ACTION360_DB.AI TO ROLE ACTION360_ANALYST;
GRANT USAGE ON SCHEMA ACTION360_DB.APP TO ROLE ACTION360_ANALYST;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACTION360_ANALYST;
